# Generated by Django 3.2.3 on 2021-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djingleshop_shopping', '0003_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(default=407091),
        ),
    ]
